### ISSUE TITLE
Crash on server: NoClassDefFound I18n

### ISSUE THREAD

**Issue by tyra314** [elytra/Correlated#58]
I'm getting a crash when trying to start my custom pack on the server.
I guess [ItemMisc::getItemStackDisplayName()](https://github.com/elytra/Correlated/blob/1.11.2/src/main/java/com/elytradev/correlated/item/ItemMisc.java#L144) is missing a ```@SideOnly(Side.CLIENT)```.

I'm using Minecraft 1.11.2, Forge 13.20.0.2282 and Correlated-1.11.2-2.0.0a4.

You can find the crash report [here](https://gist.github.com/tyra314/1d06c06276f0b050bfda14c3ece460a9)

**Comment by tyra314** [comment]
I locally fixed that one and a few others in CommandInterpreter and IBMFontRenderer, as IntellJ told me so 😨 
And made my custom build. This one seems to be working.

**Comment by unascribed** [comment]
IBMFontRenderer and CommandInterpreter are both client-only, so, non-issue.

ItemMisc is fixed in master already. There's two I18n classes; one is deprecated and works on the server, the other only works on the client. I had converted to the non-deprecated one in the 1.11 port, and I switched back when I realized it crashes on the server.

**Comment by unascribed** [comment]
Fix released as [v2.0.0a5](https://github.com/elytra/Correlated/releases/tag/1.11.2-2.0.0a5).
